LiftOffProject/Models/Quiz.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace LiftOffProject.Models
{
    public class Quiz
    {
        public int QuizId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public DateTime Published { get; set; }
        public List<Question> Questions { get; set; }
        public int TotalPoints { get; set; }



        public Quiz(string title, string author, DateTime published, List<Question> questions)
        {
            Title = title; 
            Author = author;
            Published = published;
            Questions = questions;
        }
        public Quiz(string title, string author)
        {
            Title = title;
            Author = author;
        }

        public Quiz()
        {
        }

    }
}

LiftOffProject/ViewModels/AddQuestionViewModel.cs
using LiftOffProject.Data;
using LiftOffProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LiftOffProject.ViewModels
{
    public class AddQuestionViewModel
    {
        public int QuizId { get; set; }
        public int QuestionId { get; set; }
        [Required(ErrorMessage = "Question is required.")]
        public string Query { get; set; }
        public string AnswerOne { get; set; }
        public string AnswerTwo { get; set; }

        public string CorrectAnswer { get; set; }
        public string ChosenAnswers { get; set; }
        

        //public AddQuestionViewModel(Quiz quiz)
        //{
        //    QuizId = quiz.Id;
        //}
        //public AddQuestionViewModel(Quiz quiz, List<Answers> answers)
        //{
        //    QuizId = quiz.Id;

        //    foreach (var answer in answers)
        //    {
        //        Answers.Add(new SelectListItem
        //        {
        //            Value = answer.Id.ToString(),
        //            Text = answer.Choice
        //        });
        //    }
        //}

        //public AddQuestionViewModel()
        //{
        //}
        
        //public void AddFields()
        //{

        //}
    }

}

LiftOffProject/ViewModels/QuizViewModel.cs
using LiftOffProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;

namespace LiftOffProject.ViewModels
{
    public class QuizViewModel
    {
        public int QuizId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public DateTime Published  { get; set; }
        public List<Question> Questions { get; set; }
        


        public QuizViewModel(Quiz theQuiz)
        {
            QuizId = theQuiz.QuizId;
            Title = theQuiz.Title;
            Author = theQuiz.Author;
            Published = theQuiz.Published;
            Questions = theQuiz.Questions;
        }

        public QuizViewModel()
        {
        }
    }
}

LiftOffProject/Controllers/QuizzesController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using LiftOffProject.Data;
using LiftOffProject.Models;
using LiftOffProject.ViewModels;
//using LiftOffProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;


namespace LiftOffProject.Controllers
{
    public class QuizzesController : Controller
    {
        private ApplicationDbContext context;

        public QuizzesController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }


        public IActionResult Index()
        {
            List<Quiz> quizzes = context.Quizzes
                .ToList();
            return View(quizzes);
        }

        public IActionResult Add()
        {
            AddQuizViewModel addQuizViewModel = new AddQuizViewModel();
            return View(addQuizViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddQuizViewModel addQuizViewModel)
        {
            if (ModelState.IsValid)
            {
                Quiz newQuiz = new Quiz
                {
                    Title = addQuizViewModel.Title,
                    Author = addQuizViewModel.Author,
                    Published = DateTime.Now
                };

                context.Quizzes.Add(newQuiz);
                context.SaveChanges();

                return Redirect("AddQuestions/" + newQuiz.QuizId);
            }

            return View(addQuizViewModel);
        }

        public IActionResult AddQuestions(int quizId)
        {
            Quiz quiz = context.Quizzes.Find(quizId);
            AddQuestionViewModel addQuestionViewModel = new AddQuestionViewModel();
            return View(addQuestionViewModel);
        }

        [HttpPost]
        public IActionResult AddQuestions(AddQuestionViewModel addQuestionViewModel)
        {
            if (ModelState.IsValid)
            {
                //List<Answers> theAnswers = new List<Answers>();

                //foreach (var answer in addQuestionViewModel.Answers)
                //{
                //    // this foreach loop iterates over the SelectListItem objects and converts them into Answer objects
                //    Answers newAnswer = new Answers();
                //    if (answer.Selected)
                //    {
                //        newAnswer.IsAnswer = true;
                //    }

                //    newAnswer.Text = answer.Value;

                //    theAnswers.Add(newAnswer);
                //};

                Question newQuestion = new Question
                {
                    Query = addQuestionViewModel.Query,
                    AnswerOne = addQuestionViewModel.AnswerOne,
                    AnswerTwo = addQuestionViewModel.AnswerTwo,
                    CorrectAnswer = addQuestionViewModel.CorrectAnswer,
                };
            

                context.Questions.Add(newQuestion);

                context.SaveChanges();

            }
            return View(addQuestionViewModel);
        }
   

        //    return Redirect("Index");
        //}

        [HttpGet]
        [Route("/quizzes/quiz/{quizId}")]
        public IActionResult Quiz(int quizId)
        {
            Quiz theQuiz = context.Quizzes
                .Find(quizId);

            QuizViewModel quizViewModel = new QuizViewModel(theQuiz);
            return View(quizViewModel);

        }

        [HttpPost]
        [Route("/quizzes/quiz/{quizId}")]
        public IActionResult Quiz(int quizId, string title, string author)
        {
            
            Quiz theQuiz = context.Quizzes
                .Find(quizId);


            theQuiz.Title = title;
            theQuiz.Author = author;

            context.SaveChanges();

            return Redirect("/Quizzes");
        }

        [HttpGet]
        [Route("/quizzes/delete/{quizId}")]
        public IActionResult Delete(int quizId)
        {
            Quiz theQuiz = context.Quizzes
                .Find(quizId);

            QuizViewModel quizViewModel = new QuizViewModel(theQuiz);
            return View(quizViewModel);
        }


        [HttpPost]
        [Route("/quizzes/delete/{quizId}")]
        public IActionResult Confirm(int quizId)
        {
            Quiz theQuiz = context.Quizzes.Find(quizId);
            context.Quizzes.Remove(theQuiz);

            context.SaveChanges();
            return Redirect("/Quizzes");
        }
    }
};

LiftOffProject/Views/Quizzes/Add.cshtml
@model LiftOffProject.ViewModels.AddQuizViewModel

<h1>Add Quiz</h1>

<form asp-controller="Quizzes" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" />
        <span asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" />
        <span asp-validation-for="Author"></span>
    </div>
    <a href="AddQuestions">
    <input type="submit" value="Create Quiz" />
    </a>
</form>

LiftOffProject/Views/Quizzes/AddQuestions.cshtml
@model LiftOffProject.ViewModels.AddQuestionViewModel

<h1>Add Questions</h1>

<script>

</script>

<form asp-controller="Quizzes" asp-action="AddQuestions" method="post" id="questionform" />
    <div class="form-group">
        <label asp-for="Query">Query</label>
        <input asp-for="Query" />
        <span asp-validation-for="Query"></span>
    </div>

    <label>
        <label>~Correct Answer</label><input asp-for="CorrectAnswer" type="text" name="correct" value="choice1" /><br />
        <label>Incorrect Answer</label><input asp-for="AnswerOne" type="text" name="incorrect1" value="choice2" /><br/>
        <label>Incorrect Answer</label><input asp-for="AnswerTwo" type="text" name="incorrect2" value="choice3" /><br/>
        </label><br/>
        <span></span>
    

    <button onclick={AddQuestions} id="addQuestion">Add Question</button>  




    <input type="submit" id="addQuestion" value="Finish" />

LiftOffProject/Views/Quizzes/Delete.cshtml
@model LiftOffProject.ViewModels.QuizViewModel

<h1>Confirm Delete?</h1>

<form asp-controller="Quizzes" asp-action="Delete" asp-route-id="@Model.QuizId">
    <h2>@Model.Title by: @Model.Author</h2>
    <input type="submit" value="Delete Quiz" />
</form>

LiftOffProject/Views/Quizzes/Index.cshtml
@model List<LiftOffProject.Models.Quiz>

<h1>Quizzes</h1>

<p>
    <a asp-controller="Quizzes" asp-action="Add">Add Quiz</a>
</p>

@if (Model.Count == 0)
{
    <p>No quizzes available</p>
}
else
{
    <table class="table">
        <tr>
            <th>
                Id
            </th>
            <th>
                Title
            </th>
            <th>
                Author
            </th>
            <th>
                Published
            </th>
            <th>
                Edit Quiz
            </th>
            <th>
                Delete Quiz
            </th>
        </tr>
        @foreach (var qz in Model)
        {
            <tr>
                <td>@qz.QuizId</td>
                <td>@qz.Title</td>
                <td>@qz.Author</td>
                <td>@qz.Published</td>
                <td><a asp-controller="Quizzes" asp-action="Quiz" asp-route-id="@qz.QuizId">Edit</a></td>
                <td><a asp-controller="Quizzes" asp-action="Delete" asp-route-id="@qz.QuizId">Delete</a></td>
            </tr>
        }
    </table>
}

LiftOffProject/Views/Quizzes/Quiz.cshtml
@model LiftOffProject.ViewModels.QuizViewModel

<h1>Edit @Model.Title by @Model.Author</h1>

<form method="post" asp-controller="Quizzes" asp-action="Quiz">
    <table class="table">

        <tr>
            <th>ID</th>
            <th>Quiz Name</th>
            <th>Author</th>
            <th>Published On</th>
            @*<th># Questions</th>*@
        </tr>

            <tr>
            <td name="quizId" value="@Model.QuizId">@Model.QuizId</td>
                <td>
                    <div class="form-group">
                        @*<label asp-for="@Model.Title"></label>*@
                        <input asp-for="@Model.Title" type="text" />
                    </div>
                </td>
                <td>
                    <div class="form-group">   
                        @*<label asp-for="@Model.Author"></label>*@
                        <input asp-for="@Model.Author" type="text" />
                    </div>
                </td>
                <td>@Model.Published"</td>
    @*            <td>@Model.Questions.Count</td>
                <td>@Model.TotalPoints</td>*@
            </tr>


    </table>
    <input type="hidden" value="@Model.QuizId" name="QuizId" />
    <input type="submit" value="Update" />
</form>